services:
  ffc-tech-spike-rule-engine-proxy:
    build:
      context: .
      target: production
    image: ffc-tech-spike-rule-engine-proxy
    container_name: ffc-tech-spike-rule-engine-proxy
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tech-spike-rule-engine-proxy-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      REMOTE_JBPM_URL: ${REMOTE_JBPM_URL}
