# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tech-spike-rule-engine-proxy:
    build:
      target: development
    image: ffc-tech-spike-rule-engine-proxy-development
    container_name: ffc-tech-spike-rule-engine-proxy-development
    ports:
      - "3020:3000"
      - "9240:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
